#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const manifest = require('../module-manifest.cjs');
const { getPaths } = require('../webpack/paths.cjs');

const { modulesRoot } = getPaths();

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function toImportName(viewName) {
  return viewName
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function generateEntry(packageName, config) {
  const packageDir = path.join(modulesRoot, packageName);
  const srcDir = path.join(packageDir, 'src');
  fs.mkdirSync(srcDir, { recursive: true });

  const imports = config.views.map((view, index) => {
    const varName = `routes${index}`;
    return `import ${varName} from '@views/${view}/routes';`;
  });

  const exports = config.views.map((_, index) => `routes${index}`);

  const content = `/*
  Auto-generated by packages/build-tools/scripts/generate-entries.cjs
  Package: ${packageName}
  Do not edit manually.
*/
${imports.join('\n')}

export default [
  ${exports.join(',\n  ')},
];
`;

  fs.writeFileSync(path.join(srcDir, 'entry.ts'), content, 'utf8');
  console.log(`[generate-entries] ${packageName}: ${config.views.join(', ')}`);
}

Object.entries(manifest).forEach(([packageName, config]) => {
  generateEntry(packageName, config);
});

console.log('[generate-entries] done.');
