/*
  Auto-generated by packages/build-tools/scripts/generate-entries.cjs
  Package: analysis
  Do not edit manually.
*/
import routes0 from '@views/analysis-manage/routes';
import routes1 from '@views/statement-manage/routes';

export default [
  routes0,
  routes1,
];
