/*
  Auto-generated by packages/build-tools/scripts/generate-entries.cjs
  Package: risk
  Do not edit manually.
*/
import routes0 from '@views/risk-manage/routes';
import routes1 from '@views/handle-manage/routes';
import routes2 from '@views/attention-manege/routes';
import routes3 from '@views/processed-manage/routes';
import routes4 from '@views/scene-risk-manage/routes';
import routes5 from '@views/event-manage/routes';

export default [
  routes0,
  routes1,
  routes2,
  routes3,
  routes4,
  routes5,
];
