/*
  Auto-generated by packages/build-tools/scripts/generate-entries.cjs
  Package: platform
  Do not edit manually.
*/
import routes0 from '@views/platform-manage/routes';
import routes1 from '@views/storage-manage/routes';

export default [
  routes0,
  routes1,
];
