/*
  Auto-generated by packages/build-tools/scripts/generate-entries.cjs
  Package: system
  Do not edit manually.
*/
import routes0 from '@views/system-manage/routes';
import routes1 from '@views/new-system-manage/routes';

export default [
  routes0,
  routes1,
];
