/*
  Auto-generated by packages/build-tools/scripts/generate-entries.cjs
  Package: strategy
  Do not edit manually.
*/
import routes0 from '@views/strategy-manage/routes';
import routes1 from '@views/link-data-manage/routes';
import routes2 from '@views/rule-manage/routes';
import routes3 from '@views/process-application-manage/routes';
import routes4 from '@views/notice-group/routes';

export default [
  routes0,
  routes1,
  routes2,
  routes3,
  routes4,
];
